CREATE TABLE TB_USER (
  OBJ_ID  BIGSERIAL PRIMARY KEY,
  USER_NAME varchar(64) DEFAULT NULL UNIQUE,
  AVATAR varchar(255) DEFAULT NULL,
  EMAIL varchar(64) DEFAULT NULL,
  "PASSWORD" varchar(64) DEFAULT NULL,
  STATUS int(5) NOT NULL,
  CREATED datetime DEFAULT NULL,
  LAST_LOGIN datetime DEFAULT NULL,
);